// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearAutoSave() {
  return window['go']['main']['App']['ClearAutoSave']();
}

export function CloseTerminal() {
  return window['go']['main']['App']['CloseTerminal']();
}

export function ForceClose() {
  return window['go']['main']['App']['ForceClose']();
}

export function GetFolderTree(arg1) {
  return window['go']['main']['App']['GetFolderTree'](arg1);
}

export function GetPendingFile() {
  return window['go']['main']['App']['GetPendingFile']();
}

export function LoadAutoSave() {
  return window['go']['main']['App']['LoadAutoSave']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFileChooser() {
  return window['go']['main']['App']['OpenFileChooser']();
}

export function ResizeTerminal(arg1, arg2) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2);
}

export function SaveAutoSave(arg1) {
  return window['go']['main']['App']['SaveAutoSave'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveFileChooser() {
  return window['go']['main']['App']['SaveFileChooser']();
}

export function StartTerminal() {
  return window['go']['main']['App']['StartTerminal']();
}

export function WriteTerminal(arg1) {
  return window['go']['main']['App']['WriteTerminal'](arg1);
}
