// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearAutoSave():Promise<void>;

export function CloseTerminal():Promise<void>;

export function ForceClose():Promise<void>;

export function GetFolderTree(arg1:string):Promise<Array<main.FileNode>>;

export function GetPendingFile():Promise<string>;

export function GetVersion():Promise<string>;

export function LoadAutoSave():Promise<string>;

export function OpenFile(arg1:string):Promise<string>;

export function OpenFileChooser():Promise<string>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function ResizeTerminal(arg1:number,arg2:number):Promise<void>;

export function SaveAutoSave(arg1:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveFileChooser():Promise<string>;

export function StartTerminal():Promise<void>;

export function WriteTerminal(arg1:string):Promise<void>;
